import os
import unittest
from mltools.utils.utils import parse_string_as_path

# AUTOGENERATED TESTS TODO: CHECK IF THEY ARE CORRECT

class TestUtils(unittest.TestCase):

    def setUp(self):
        # Create a temporary file for testing
        self.test_file = 'test_file.txt'
        with open(self.test_file, 'w') as f:
            f.write('test content')

    def tearDown(self):
        # Remove the temporary file after tests
        if os.path.exists(self.test_file):
            os.remove(self.test_file)

    def test_parse_string_as_path_existing_file(self):
        result = parse_string_as_path(self.test_file)
        expected = os.path.join(os.getcwd(), self.test_file)
        self.assertEqual(result, expected)

    def test_parse_string_as_path_nonexistent_file(self):
        result = parse_string_as_path('nonexistent_file.txt')
        self.assertIsNone(result)

    def test_parse_string_as_path_empty_string(self):
        result = parse_string_as_path('')
        self.assertIsNone(result)

    def test_parse_string_as_path_none(self):
        result = parse_string_as_path(None)
        self.assertIsNone(result)

if __name__ == '__main__':
    unittest.main()